spring.application.name=SpringSecurity

spring.security.user.name = ganesh
spring.security.user.password =test1

spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security-db
spring.datasource.username=postgres
spring.datasource.password=12345

server.port=8081